name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_x86:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: docker hub login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ vars.DOCKERHUB_USER }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.DOCKERHUB_USER }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-x86

    - name: Push the Docker image
      run: docker push ${{ vars.DOCKERHUB_USER }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-x86
