name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_x86:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: docker hub login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u mmalzahn --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mmalzahn/wfsdebugger:${{ github.ref_name }}-x86

    - name: Push the Docker image
      run: docker push mmalzahn/wfsdebugger:${{ github.ref_name }}-x86
